# action.yml
name: 'jUnit XML to HTML'
description: 'Convert jUnit XML to HTML'
branding:
  icon: 'award'
  color: 'green'
inputs:
  mode:
    description: 'Either "frames" or "no-frames"'
    required: true
    default: 'no-frames'
  input:
    description: 'Input XML file'
    required: true
  output:
    description: 'Output HTML file or directory'
    required: true
runs:
  using: 'composite'
  steps:
    - id: action
      run: |
        echo "owner=$(jq -jn 'env.GITHUB_ACTION_PATH | split("/") | .[5]')" >> $GITHUB_OUTPUT
        echo "repo=$(jq -jn 'env.GITHUB_ACTION_PATH | split("/") | .[6]')" >> $GITHUB_OUTPUT
        echo "ref=$(jq -jn 'env.GITHUB_ACTION_PATH | split("/") | .[7:] | join("/")')" >> $GITHUB_OUTPUT
      shell: bash
    - uses: pl-strflt/docker-container-action@v1
      env:
        INPUT_MODE: ${{ inputs.mode }}
        INPUT_INPUT: ${{ inputs.input }}
        INPUT_OUTPUT: ${{ inputs.output }}
      with:
        repository: ${{ steps.action.outputs.owner }}/${{ steps.action.outputs.repo }}
        ref: ${{ steps.action.outputs.ref }}
        args: $INPUT_MODE $INPUT_INPUT $INPUT_OUTPUT
