# action.yml
name: 'jUnit XML to HTML'
description: 'Convert jUnit XML to HTML'
branding:
  icon: 'award'
  color: 'green'
inputs:
  mode:
    description: 'Either "frames" or "no-frames"'
    required: true
    default: 'no-frames'
  input:
    description: 'Input XML file'
    required: true
  output:
    description: 'Output HTML file or directory'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        echo ${{ toJSON(env) }}
        echo ${{ toJSON(github) }}
      shell: bash
    - uses: pl-strflt/docker-container-action@v1
      env:
        INPUT_MODE: ${{ inputs.mode }}
        INPUT_INPUT: ${{ inputs.input }}
        INPUT_OUTPUT: ${{ inputs.output }}
      with:
        repository: ${{ env.GITHUB_ACTION_REPOSITORY || github.repository }}
        ref: ${{ env.GITHUB_ACTION_REF || github.sha }}
        args: $INPUT_MODE $INPUT_INPUT $INPUT_OUTPUT
