# action.yml
name: 'jUnit XML to HTML'
description: 'Convert jUnit XML to HTML'
branding:
  icon: 'award'
  color: 'green'
inputs:
  mode:
    description: 'Either "frames" or "no-frames"'
    required: true
    default: 'no-frames'
  input:
    description: 'Input XML file'
    required: true
  output:
    description: 'Output HTML file or directory'
    required: true
runs:
  using: 'composite'
  steps:
    - id: action
      run: |
        if [[ $GITHUB_ACTION_PATH == */_actions/* ]]; then
          echo "repository=$(echo ${GITHUB_ACTION_PATH#*/_actions/} | cut -d/ -f1-2)" >> $GITHUB_OUTPUT
          echo "ref=$(echo ${GITHUB_ACTION_PATH#*/_actions/} | cut -d/ -f3)" >> $GITHUB_OUTPUT
        else
          echo "repository=$GITHUB_REPOSITORY" >> $GITHUB_OUTPUT
          echo "ref=$GITHUB_SHA" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - uses: pl-strflt/docker-container-action@v1
      env:
        INPUT_MODE: ${{ inputs.mode }}
        INPUT_INPUT: ${{ inputs.input }}
        INPUT_OUTPUT: ${{ inputs.output }}
      with:
        repository: ${{ steps.action.outputs.repository }}
        ref: ${{ steps.action.outputs.ref }}
        args: $INPUT_MODE $INPUT_INPUT $INPUT_OUTPUT
