# action.yml
name: 'JUnit XML to HTML'
description: 'Convert JUnit XML to HTML'
branding:
  icon: 'award'
  color: 'green'
inputs:
  mode:
    description: 'Either "frames" or "no-frames"'
    required: true
    default: 'no-frames'
  input:
    description: 'Input XML file'
    required: true
  output:
    description: 'Output HTML file or directory'
    required: true
runs:
  using: 'composite'
  steps:
    - if: inputs.mode == 'frames'
      uses: pl-strflt/saxon@v1
      env:
        INPUT_INPUT: ${{ inputs.input }}
        INPUT_OUTPUT: ${{ inputs.output }}
      with:
        args: -s:$INPUT_INPUT -xsl:/etc/junit-frames-saxon.xsl output.dir=/github/workspace/$INPUT_OUTPUT
    - if: inputs.mode == 'no-frames'
      uses: pl-strflt/saxon@v1
      env:
        INPUT_INPUT: ${{ inputs.input }}
        INPUT_OUTPUT: ${{ inputs.output }}
      with:
        args: -s:$INPUT_INPUT -xsl:/etc/junit-noframes-saxon.xsl -o:$INPUT_OUTPUT
