# action.yml
name: 'jUnit XML to HTML'
description: 'Convert jUnit XML to HTML'
branding:
  icon: 'award'
  color: 'green'
inputs:
  mode:
    description: 'Either "frames" or "no-frames"'
    required: true
    default: 'no-frames'
  input:
    description: 'Input XML file'
    required: true
  output:
    description: 'Output HTML file or directory'
    required: true
runs:
  using: 'composite'
  steps:
    - id: github
      uses: pl-strflt/docker-container-action/.github/actions/github@v1
    - uses: pl-strflt/docker-container-action@v1
      env:
        INPUT_MODE: ${{ inputs.mode }}
        INPUT_INPUT: ${{ inputs.input }}
        INPUT_OUTPUT: ${{ inputs.output }}
      with:
        repository: ${{ steps.github.outputs.action_repository }}
        ref: ${{ steps.github.outputs.action_ref }}
        args: $INPUT_MODE $INPUT_INPUT $INPUT_OUTPUT
